import fs from 'node:fs/promises';
import { Presentation, PresentationFile } from '@oai/artifact-tool';

const OUT='C:/Users/sharm/OneDrive/Documents/personal-projects/meet-ai-vis/yc-deck-work';
const W=1280,H=720; const C={bg:'#FBF9F6',ink:'#1A1512',muted:'#6F6862',orange:'#FB8500',mint:'#10B981',line:'#DED8D1',pale:'#F2ECE4',white:'#FFFFFF'};
function shp(s,x,y,w,h,fill='none',stroke='none',geom='roundRect'){return s.shapes.add({geometry:geom,position:{left:x,top:y,width:w,height:h},fill,line:{style:'solid',fill:stroke,width:stroke==='none'?0:1},borderRadius:'rounded-xl'});}
function tx(s,v,x,y,w,h,fs,color=C.ink,b=false,face='Aptos'){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{style:'solid',fill:'none',width:0}});t.text=v;t.text.fontSize=fs;t.text.color=color;t.text.bold=b;t.text.typeface=face;t.text.verticalAlignment='top';t.text.insets={left:0,right:0,top:0,bottom:0};return t;}
function ln(s,x1,y1,x2,y2,c=C.line,w=2){s.shapes.add({geometry:'line',position:{left:x1,top:y1,width:x2-x1,height:y2-y1},line:{style:'solid',fill:c,width:w}});}
function ft(s,n){tx(s,'STASH LIVE  /  YC APPLICATION',72,676,400,18,12,C.muted,true,'Aptos Mono');tx(s,String(n).padStart(2,'0'),1180,676,28,18,12,C.muted,true,'Aptos Mono');}
function hd(s,k,h,sub=''){const dark=['THE PRODUCT','ALTERNATIVES','BUSINESS MODEL','RISKS'].includes(k);tx(s,k.toUpperCase(),72,54,600,20,13,C.orange,true,'Aptos Mono');tx(s,h,72,94,1110,86,37,dark?C.bg:C.ink,true,'Aptos Display');if(sub)tx(s,sub,72,188,1040,42,19,dark?C.pale:C.muted,false,'Aptos');}
function notes(s,n='No external sources. Claims and metrics are based on the current Stash Live prototype or are explicitly labeled hypotheses/targets.'){if(s.addNotes)s.addNotes(`[Sources]\n${n}`);}
const p=Presentation.create({slideSize:{width:W,height:H}});

// 1 Positioning
{const s=p.slides.add();s.background.fill=C.bg;tx(s,'STASH LIVE',72,70,500,28,16,C.orange,true,'Aptos Mono');tx(s,'Voice-triggered proof\nfor sales engineers.',72,145,760,124,54,C.ink,true,'Aptos Display');tx(s,'Surface approved security and performance proof during live customer calls—without breaking demo flow.',76,304,770,60,23,C.muted);ln(s,76,420,520,420,C.orange,5);tx(s,'ICP',76,454,80,20,13,C.orange,true,'Aptos Mono');tx(s,'Mid-market B2B SaaS teams running security-heavy demos and QBRs.',160,450,650,28,20,C.ink,true);shp(s,900,132,270,380,C.ink);tx(s,'SOC 2\nREADY',936,208,190,76,36,C.bg,true,'Aptos Display');tx(s,'appears when\n“security” is spoken',936,330,190,62,18,C.pale);tx(s,'approved proof  /  low interruption',936,465,215,20,12,C.orange,true,'Aptos Mono');ft(s,1);notes(s);}

// 2 Problem with target-labelled numbers
{const s=p.slides.add();s.background.fill=C.bg;hd(s,'THE PROBLEM','A proof request breaks the presenter’s flow.','Observed sequence to measure in pilots; numbers below are validation targets, not current claims.');const steps=[['01','Prospect asks','“What is your uptime / SOC 2 status?”'],['02','Presenter switches','Target: 20–30 seconds to find the approved answer'],['03','Attention breaks','Target: 2 proof interruptions per eligible demo'],['04','Proof lands late','Target: improve recall / objection handling—measure, don’t assume']];let y=288;for(const [n,a,b] of steps){tx(s,n,82,y,48,26,15,C.orange,true,'Aptos Mono');tx(s,a,160,y,230,28,21,C.ink,true);tx(s,b,430,y,650,28,19,C.muted);ln(s,82,y+52,1110,y+52,C.line,1);y+=75;}ft(s,2);notes(s);}

// 3 Product before/after
{const s=p.slides.add();s.background.fill=C.ink;hd(s,'THE PRODUCT','The full demo stays. One proof point appears beside it.');tx(s,'BEFORE',92,292,160,22,13,C.orange,true,'Aptos Mono');shp(s,92,330,430,190,C.pale);tx(s,'Presenter pauses\n→ searches Notion\n→ shares a tab',125,365,310,110,28,C.ink,true,'Aptos Display');tx(s,'AFTER',710,292,160,22,13,C.orange,true,'Aptos Mono');shp(s,710,330,430,190,C.bg);tx(s,'Presenter keeps talking',740,355,280,26,21,C.muted,true);shp(s,740,400,310,82,C.ink);tx(s,'99.99% uptime',765,420,250,30,27,C.bg,true,'Aptos Display');tx(s,'approved card · transient overlay',765,462,250,18,13,C.orange,true,'Aptos Mono');tx(s,'Voice/topic match  →  approved asset library  →  transient overlay  →  dismiss + audit trail',92,590,950,28,18,C.pale);ft(s,3);notes(s);}

// 4 wedge
{const s=p.slides.add();s.background.fill=C.bg;hd(s,'THE WEDGE','Start where proof requests are frequent, sensitive, and repeatable.','Security-heavy demos and QBRs for mid-market B2B SaaS.');const cols=[['MOTION','Technical demo\nSecurity review\nQBR'],['PROOF','SOC 2\nUptime\nArchitecture\nCompliance'],['TARGET CATEGORIES','Dev tools\nData infrastructure\nSecurity software']];let x=82;for(const [a,b] of cols){shp(s,x,300,310,210,C.pale);tx(s,a,x+28,330,240,22,13,C.orange,true,'Aptos Mono');tx(s,b,x+28,372,240,110,26,C.ink,true,'Aptos Display');x+=360;}tx(s,'Example target categories—not customer logos or current traction.',82,574,720,24,16,C.muted,false,'Aptos');ft(s,4);notes(s);}

// 5 alternatives
{const s=p.slides.add();s.background.fill=C.ink;hd(s,'ALTERNATIVES','We are not replacing presentation. We remove the interruption around it.');const rows=[['SCREEN SHARING','Rich context, but the presenter leaves the conversation'],['TAB STASHING','Fast for the presenter, invisible and inconsistent for the audience'],['AI COPILOTS','Often private notes or answers—not approved visual proof'],['STASH LIVE','Real-time, approved, transient proof beside the speaker']];let y=285;for(const [a,b] of rows){tx(s,a,90,y,250,24,15,C.orange,true,'Aptos Mono');tx(s,b,380,y,720,28,21,a==='STASH LIVE'?C.bg:C.pale,a==='STASH LIVE');ln(s,90,y+54,1110,y+54,'#4A4038',1);y+=75;}ft(s,5);notes(s);}

// 6 feasibility
{const s=p.slides.add();s.background.fill=C.bg;hd(s,'FEASIBILITY','The hard product path is already crossed. Now we need usage proof.');const items=[['LIVE','Topic matching, transcript window, cooldown and dismiss controls'],['TRUST','Approved cards, drafts, privacy controls, activity audit trail'],['INTEGRATION','Google Meet extension, Notion sync, rendered overlays']];let y=298;for(const [a,b] of items){tx(s,a,90,y,160,24,15,C.orange,true,'Aptos Mono');tx(s,b,300,y,760,28,22,C.ink,true);ln(s,90,y+54,1110,y+54,C.line,1);y+=82;}tx(s,'We will keep technical detail in the appendix. The investor question now is repeatability.',90,575,900,28,18,C.muted);ft(s,6);notes(s,'Current capabilities are based on the Stash Live repository: matching, extension, Notion, cards, privacy, activity, and rendering modules.');}

// 7 business model/TAM
{const s=p.slides.add();s.background.fill=C.ink;hd(s,'BUSINESS MODEL','Team SaaS, priced against demo productivity and consistency.','Initial pricing and TAM are hypotheses to test—not revenue or market claims.');shp(s,82,286,450,220,C.bg);tx(s,'PRICING HYPOTHESIS',112,320,260,22,13,C.orange,true,'Aptos Mono');tx(s,'$1.5k–$3k',112,365,310,50,42,C.ink,true,'Aptos Display');tx(s,'per team / month\n10 seats · two-week pilot first',112,430,280,52,18,C.muted);shp(s,610,286,540,220,'#2A2420');tx(s,'BOTTOM-UP TAM FORMULA',642,320,310,22,13,C.orange,true,'Aptos Mono');tx(s,'target companies × SE seats × $/seat/month × adoption',642,367,430,46,25,C.bg,true,'Aptos Display');tx(s,'Start with one segment and replace assumptions with sourced counts.',642,444,400,40,18,C.pale);tx(s,'ROI hypothesis: fewer context switches + more consistent approved proof. Measure completion, recall, and SQO impact.',82,570,980,28,18,C.pale);ft(s,7);notes(s);}

// 8 validation table
{const s=p.slides.add();s.background.fill=C.bg;hd(s,'VALIDATION','The pilot succeeds only if behavior changes.');const rows=[['REPEAT USE','3+ SEs at one logo use Stash in 60%+ of eligible moments across 10+ meetings'],['TRIGGER ACCURACY','90%+ correct card selection; false positives tracked and reviewed'],['USER VALUE','Presenter reports fewer searches and wants to keep the workflow'],['WILLINGNESS TO PAY','Two-week pilot converts to $1.5k–$3k/team/month paid plan']];let y=286;for(const [a,b] of rows){shp(s,82,y,200,54,C.ink);tx(s,a,104,y+17,165,20,13,C.orange,true,'Aptos Mono');tx(s,b,322,y+5,790,44,18,C.ink,true);y+=72;}tx(s,'Targets are intentionally demanding; the point is to earn the next segment.',82,590,760,24,17,C.muted);ft(s,8);notes(s);}

// 9 risks
{const s=p.slides.add();s.background.fill=C.ink;hd(s,'RISKS','Trust is the product. We design for the two ways it can fail.');const risks=[['WRONG MOMENT','False positive or stale card','Mitigation: confidence thresholds, cooldowns, one-click dismiss, presenter override'],['WRONG DATA','Sensitive or unapproved information appears','Mitigation: approved asset library, drafts, access controls, audit trail']];let x=82;for(const [a,b,c] of risks){shp(s,x,295,500,230,'#2A2420');tx(s,a,x+28,330,300,22,13,C.orange,true,'Aptos Mono');tx(s,b,x+28,370,410,34,27,C.bg,true,'Aptos Display');tx(s,c,x+28,440,420,48,17,C.pale);x+=570;}tx(s,'The prototype already includes cooldown, dismiss, approval, and activity-control primitives.',82,585,960,26,18,C.pale);ft(s,9);notes(s);}

// 10 ask
{const s=p.slides.add();s.background.fill=C.bg;tx(s,'THE ASK',72,70,500,20,13,C.orange,true,'Aptos Mono');tx(s,'Help us find the first\n10 teams that need this.',72,124,820,112,51,C.ink,true,'Aptos Display');tx(s,'We are looking for introductions to Heads of Sales Engineering at mid-market SaaS companies selling security-sensitive products.',76,290,820,62,22,C.muted);ln(s,76,420,520,420,C.orange,5);tx(s,'PILOT',76,456,100,22,13,C.orange,true,'Aptos Mono');tx(s,'Two weeks · 10 seats · success criteria agreed upfront',160,452,700,28,21,C.ink,true);tx(s,'PAID CONVERSION',76,516,150,22,13,C.orange,true,'Aptos Mono');tx(s,'$1.5k–$3k per team / month hypothesis',260,512,600,28,21,C.ink,true);tx(s,'STASH LIVE',936,570,220,28,16,C.orange,true,'Aptos Mono');tx(s,'Proof, at the moment it matters.',936,610,250,24,16,C.muted);ft(s,10);notes(s);}

await fs.mkdir(OUT,{recursive:true});const pptx=await PresentationFile.exportPptx(p);await pptx.save(`${OUT}/stash-live-yc-pitch-deck-v2.pptx`);for(const [i,sl] of p.slides.items.entries()){const png=await p.export({slide:sl,format:'png',scale:1});await fs.writeFile(`${OUT}/v2-slide-${String(i+1).padStart(2,'0')}.png`,new Uint8Array(await png.arrayBuffer()));}
