/**
 * Mock generation provider (plan §3.2).
 *
 * Deterministic draft derived from the prompt's topic. Used by STASH_LOCAL
 * and every test. Never makes network calls.
 */
import type { GenerationProvider, AiProviderId, StructuredRequest, StructuredResult } from './provider.js';
import { GenerationProviderError, GenerationTimeoutError } from './provider.js';

export interface MockGenerationOpts {
  /** Override the returned draft (or undefined for the default). */
  draft?: unknown;
  /** Force a specific failure mode for testing. */
  failMode?: 'timeout' | 'garbage' | 'http';
}

export class MockGenerationProvider implements GenerationProvider {
  readonly id: AiProviderId = 'mock';
  readonly model = 'mock-model/v0';

  constructor(private opts?: MockGenerationOpts) {}

  async generateStructured(_req: StructuredRequest): Promise<StructuredResult> {
    if (this.opts?.failMode === 'timeout') {
      // The caller is expected to wrap with withGenerationTimeout; hanging forever is fine.
      return new Promise<never>(() => {});
    }

    if (this.opts?.failMode === 'garbage') {
      return {
        json: null,
        raw: 'definitely not json {{{',
        provider: 'mock',
        model: this.model,
      };
    }

    if (this.opts?.failMode === 'http') {
      throw new GenerationProviderError('Mock HTTP error', true, 500);
    }

    const draft = this.opts?.draft ?? {
      relevant: true,
      sourceIndex: 0,
      title: 'Mock Generated Card',
      subtitle: 'This is a deterministic mock card for local dev and testing',
      accent: 'amber',
      layout: 'explainer',
      imageWanted: false,
      blocks: [
        {
          kind: 'text',
          paragraphs: ['This mock card was generated by the MockGenerationProvider. It is deterministic and requires no network access.'],
        },
        {
          kind: 'bullets',
          items: ['Deterministic output', 'No credentials needed', 'Works with STASH_LOCAL=1'],
        },
      ],
    };

    return {
      json: draft,
      raw: JSON.stringify(draft),
      provider: 'mock',
      model: this.model,
    };
  }
}
